name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    if: |
      github.event_name == 'issues' ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: |
            Thank you for submitting your first issue to the DroidGit project! Please provide detailed information about your issue, including device specifications and steps to reproduce. :)
            
            感谢您向 DroidGit 项目提交第一个问题！请提供有关问题的详细信息，包括设备规格和重现步骤。 :)
            
            Merci d'avoir soumis votre premier problème au projet DroidGit ! Veuillez fournir des informations détaillées sur votre problème, y compris les spécifications de l'appareil et les étapes à reproduire. :)
            
            DroidGit 프로젝트에 첫 이슈를 제출해 주셔서 감사합니다! 장치 사양 및 재현 단계를 포함한 문제에 대한 자세한 정보를 제공해 주세요. :)
            
            DroidGit プロジェクトに最初の issue を提出していただきありがとうございます！デバイスの仕様や再現手順など、問題の詳細情報を提供してください。 :)
          pr_message: |
            Thank you for making your first pull request to the DroidGit project! We greatly appreciate your enthusiasm to contribute and will review this as soon as we can.
            
            感谢您向 DroidGit 项目提交第一个拉取请求！我们非常感谢您的贡献热情，将尽快进行审核。
            
            Merci d'avoir fait votre première pull request sur le projet DroidGit ! Nous apprécions grandement votre enthousiasme à contribuer et nous ferons une revue dès que possible.
            
            DroidGit 프로젝트에 첫 번째 풀 리퀘스트를 만들어 주셔서 감사합니다! 기여에 대한 열의를 높이 평가하며 곧 검토하겠습니다.
            
            DroidGit プロジェクトに最初のプルリクエストを提出していただきありがとうございます！貢献への熱意を大変感謝しており、できるだけ早くレビューします。
